name: Build & Push lsst/sciplat-lab

on:
  workflow_dispatch: {}
  push:
    branches:
      - deploy
    paths:
      - 'science-containers/Dockerfiles/lsst-science-platform/**'
      - '.github/workflows/lsst-sciplat-deploy.yml'

permissions:
  contents: read

env:
  REGISTRY: images.canfar.net
  IMAGE: lsst/sciplat-lab

jobs:
  build:
    # Repository name-guard to prevent this workflow from running on forks
    if: ${{ github.repository == 'ijiraq/scicon' }}
    name: Build and Push LSST Science Platform
    runs-on: ubuntu-latest
    permissions:
      attestations: write # Attest the build provenance
      id-token: write # Generate OIDC token for cosign
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1
    
      - name: Science Platform Release Version
        id: upstream
        run: |
          version=latest_release          
          echo "version=$version" >> $GITHUB_OUTPUT
      
      - name: Echo Version
        run: |
          echo "Building sciplat-lab Version: ${{ steps.upstream.outputs.version }}"
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          registry: images.canfar.net
          username: ${{ secrets.CANFAR_USERNAME }}
          password: ${{ secrets.CANFAR_IMAGES_TOKEN }}
      
      - name: Build & Push lsst/sciplat-lab
        id: build
        uses: docker/build-push-action@v6.16.0
        with:
          context: science-containers/Dockerfiles/lsst-science-platform
          file: science-containers/Dockerfiles/lsst-science-platform/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ steps.upstream.outputs.version }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          sbom: true
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE }}
            org.opencontainers.image.description='LSST Science Platform'
            org.opencontainers.image.version=${{ steps.upstream.outputs.version }}
            org.opencontainers.image.source=https://github.com/opencadc/science-containers

      - name: Attest Image
        id: attest
        uses: actions/attest-build-provenance@v2.3.0
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          subject-digest: ${{ steps.build.outputs.digest }}
          # push-to-registry: true
          show-summary: true
      - name: Install Cosign
        id: install-cosign
        uses: sigstore/cosign-installer@v3.8.2
        with:
          cosign-release: 'v2.4.3'
      - name: Cosign Container Image
        id: cosign
        run: |
          cosign version
          cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE }}@${{ steps.build.outputs.digest }} --upload
